### ISSUE TITLE
Field name consistency

### ISSUE THREAD

**Issue by slevin** [purescript-web/purescript-canvas#22]
I'm super new to Purescript, but working with this library the first time, I did run into the fact that type Rectangle uses "w" and "h" for width and height but type Dimension uses "width" and "height", and TextMetrics uses "width". Given the touted benefits of row polymorphism; wouldn't it be better if they were consistent? I'm aware this would break a lot of existing code, though. I'm happy to make a PR for it if you like.

**Comment by paf31** [comment]
Sounds good. There are a bunch of small, irritating issues with this library, like the inconsistent argument order in functions, for example.

If you make a PR, I'll try to fix a few of these issues in one major release.

Thanks!
