### ISSUE TITLE
Move to purescript-web?

### ISSUE THREAD

**Issue by garyb** [purescript-web/purescript-canvas#44]

**Comment by paf31** [comment]
I assume purescript-web exists to collect HTML5 APIs like purescript-node does for Node APIs? I'd be fine with that.

I'd like to add a LICENSE file first though.

**Comment by garyb** [comment]
That was the idea yeah :)

**Comment by paf31** [comment]
The problem I have is that a package like drawing is then going to depend on something outside contrib. It seems nice to me if we could have contrib only depend on contrib.

What's the advantage of having more organizations? It groups things but I think t could actually hurt discoverability.

**Comment by garyb** [comment]
> The problem I have is that a package like drawing is then going to depend on something outside contrib. It seems nice to me if we could have contrib only depend on contrib.

We already have that all over the place in contrib, `drawing` already depends on `colors` for example.

> What's the advantage of having more organizations? It groups things but I think t could actually hurt discoverability.

How so? Instead of a random sea of projects that are unrelated, having `purescript-node` and  `purescript-web` at least groups things by platform. That was the original motivation behind `purescript-node` really: you know if you choose a project in there, it'll only work in Node. Likewise if it only works in the browser, it seems sensible to have it under `-web` - ideally everything in core and contrib would compile with any backend even.

**Comment by paf31** [comment]
You're right, it makes sense to identify libraries which only work in the browser. I don't know if that necessarily means that they need to be in their own organization though. I think of orgs as for managing teams of users, not libraries.

**Comment by paf31** [comment]
I don't feel terribly strongly, by the way, I just wanted to discuss because it seems like maybe just another thing to manage.

**Comment by garyb** [comment]
Sure, I'm not too fussed either really :smile:

**Comment by gabejohnson** [comment]
I've been waiting on the switch to `Effect` to tease apart `-dom` into a few other libs https://github.com/purescript-web/purescript-dom/pull/141, https://github.com/purescript-web/purescript-web-storage/pull/1, https://github.com/purescript-web/purescript-web-socket/pull/1.

I think it make sense to group the low-level bindings to the brower API into a single project.

**Comment by hdgarrood** [comment]
:+1: let's do it.

**Comment by garyb** [comment]
Done!
