### ISSUE TITLE
Supporting anti-clockwise arcs

### ISSUE THREAD

**Issue by karljs** [purescript-web/purescript-canvas#57]
I would like to see support for the optional parameter to the `arc` function that allows drawing anti-clockwise arcs (see [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arc))

Adding another parameter (such as `Maybe Bool`) to the `Arc` type breaks backwards compatibility for folks, so I don't know how the maintainers feel about that.  It might be possible to establish some standard alternative approach based on an extensible record.

Thoughts?

**Comment by paf31** [comment]
What's the difference between setting this flag and flipping the two angle arguments?
