### ISSUE TITLE
Fix field names in Transform

### ISSUE THREAD

**Issue by artemisSystem** [purescript-web/purescript-canvas#72]
`Transform` currently looks like this:
```purescript
type Transform =
  { m11 :: Number
  , m12 :: Number
  , m21 :: Number
  , m22 :: Number
  , m31 :: Number
  , m32 :: Number
  }
```
It doesn't cause any problems currently, because the arguments are just passed in order to `ctx.transform` and `ctx.setTransform`. But, the names of the last two fields are wrong, which can lead to confusion.

In [`setTransform`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setTransform#parameters) and [`transform`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/transform#parameters) (MDN docs links), they are primarily referred to as `a, b, c, d, e, f`, but also as `m11, m12, m21, m22, dx, dy`.

Also, `ctx.getTransform` returns a [`DOMMatrix`](https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrix#properties), whose docs page mentions that `e` and `f` are equivalent to `m41` and `m42` respectively, and that `m31` and `m32` mean something completely different, relating to 3D transformations.

I remember talking briefly about this in Slack with Phil a while ago, but forgot to open an issue/PR for it.

I think the best solution would be to change `Transform` to look like this:
```purescript
type Transform =
  { a :: Number
  , b :: Number
  , c :: Number
  , d :: Number
  , e :: Number
  , f :: Number
  }
```
Would this be reasonable to have as a breaking change for 0.14? I can make a PR for it if wanted.

**Comment by JordanMartinez** [comment]
I'm not familiar enough with this domain to respond.

**Comment by artemisSystem** [comment]
Do you know who would be? It would be nice to get this change in for 0.15, since it looks like you're suggesting/wanting to make some other breaking changes as well

**Comment by JordanMartinez** [comment]
I read through the links you posted and looked through the FFI. I also looked through #61. I agree that it makes sense to make your suggested change. Could you submit a PR?

**Comment by artemisSystem** [comment]
Thanks! Yes, i'll try to remember to make a PR later today or tomorrow
